### ISSUE TITLE
"Reload Extension" omnipresent in the top left of my calendar

### ISSUE THREAD

**Issue by grantfitzsimmons** [maxxxxxdlp/calendar-plus#215]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/37256050/232070149-1f004d48-4a27-44e9-9753-447c1c6b0f7f.png">

**Comment by maxxxxxdlp** [comment]
This was because I accidentally published the extension in the development mode rather than in production. Should be fixed now (or as soon as Google reviews the new version of the extension, publishes it and your browser installs it).

I will leave this issue open because I need to improve the extension publishing process (right now it's manual and thus error prone)
